In [1]:
distance = [10,20,30,40,50]
time = [1,2,3.4,5,10]

In [11]:
import numpy as np

In [12]:
np_distance = numpy.array(distance)

In [13]:
np_time = numpy.array(time)

In [14]:
speed = np_distance / np_time

In [15]:
speed

array([ 10.        ,  10.        ,   8.82352941,   8.        ,   5.        ])

In [21]:
print (numpy.linspace(15,225,15))

[  15.   30.   45.   60.   75.   90.  105.  120.  135.  150.  165.  180.
  195.  210.  225.]


# Class Attributes

In [22]:
city = np.array(['Mumbai','Pune','Delhi','Kolkata','Chennai'])

In [23]:
city.ndim

1

In [26]:
city_with_state = np.array([['Mumbai','Pune','Delhi','Kolkata','Chennai'],['Maharashtra','Maharashtra','NCR','West Bengal','Tamil Nadu']])

In [27]:
city_with_state

array([['Mumbai', 'Pune', 'Delhi', 'Kolkata', 'Chennai'],
       ['Maharashtra', 'Maharashtra', 'NCR', 'West Bengal', 'Tamil Nadu']], 
      dtype='|S11')

In [28]:
city_with_state.ndim

2

In [45]:
city_with_state_population = np.array([[['Mumbai','Pune','Delhi','Kolkata','Chennai_Express']],[['Maharashtra','Maharashtra','NCR','West Bengal','Tamil Nadu']],[[11,233,1233,1233,122]]])

In [46]:
city_with_state_population.ndim

3

In [47]:
city_with_state_population

array([[['Mumbai', 'Pune', 'Delhi', 'Kolkata', 'Chennai_Express']],

       [['Maharashtra', 'Maharashtra', 'NCR', 'West Bengal', 'Tamil Nadu']],

       [['11', '233', '1233', '1233', '122']]], 
      dtype='|S15')

In [37]:
city_with_state_population.shape

(3, 1, 5)

In [38]:
city_with_state.shape

(2, 5)

In [39]:
city.shape

(5,)

In [41]:
city_with_state_population.size
#city_with_state.size
#city.size

15

In [43]:
city_with_state.size

10

In [44]:
city.size

5

In [48]:
a = [10,20,30,40]
b=[20,40,60,80]

In [49]:
np_a = np.array(a)
np_b = np.array(b)

In [50]:
summation = np_a+np_b

In [51]:
summation

array([ 30,  60,  90, 120])

In [52]:
aa = np.array([[10,20,30,40],[15,25,35,45]])

In [53]:
check_a = aa[1]

In [54]:
check_a

array([15, 25, 35, 45])

In [55]:
check_b = aa[0]
check_b

array([10, 20, 30, 40])

In [56]:
specific_aa = aa[0][3]

In [57]:
specific_aa

40

In [62]:
specific_ab = aa[:,2]

In [63]:
specific_ab

array([30, 35])

In [64]:
specific_ab.shape

(2,)

In [65]:
aa.shape

(2, 4)

In [67]:
aa.size

8

In [68]:
abc = aa[:,1:3]

In [69]:
abc

array([[20, 30],
       [25, 35]])

In [70]:
for incre in aa:
    print (incre)

[10 20 30 40]
[15 25 35 45]


In [71]:
priority = aa>30

In [72]:
priority

array([[False, False, False,  True],
       [False, False,  True,  True]], dtype=bool)

In [73]:
aa[priority]

array([40, 35, 45])

In [76]:
A = np.array(['Naman','Anant','Upal','Rajesh'])

In [77]:
   view_of_A = A.view()

In [78]:
view_of_A

array(['Naman', 'Anant', 'Upal', 'Rajesh'], 
      dtype='|S6')

In [79]:
A

array(['Naman', 'Anant', 'Upal', 'Rajesh'], 
      dtype='|S6')

In [80]:
len(view_of_A)

4

In [81]:
len(A)

4

In [83]:
view_of_A[3]='Jai Prakash'

In [84]:
view_of_A

array(['Naman', 'Anant', 'Upal', 'Jai Pr'], 
      dtype='|S6')

In [85]:
A

array(['Naman', 'Anant', 'Upal', 'Jai Pr'], 
      dtype='|S6')

In [86]:
A = np.array(['Naman','Anant','Upal','Rajesh'])

In [87]:
B = A

In [88]:
B

array(['Naman', 'Anant', 'Upal', 'Rajesh'], 
      dtype='|S6')

In [89]:
A

array(['Naman', 'Anant', 'Upal', 'Rajesh'], 
      dtype='|S6')

In [90]:
B[3]='Padma'

In [91]:
B

array(['Naman', 'Anant', 'Upal', 'Padma'], 
      dtype='|S6')

In [92]:
A

array(['Naman', 'Anant', 'Upal', 'Padma'], 
      dtype='|S6')

In [93]:
participant_names = np.array(['Ganesh','Siva','Murthuza','Anant','Padma'])

In [94]:
copy_participant_names = participant_names.copy()

In [95]:
participant_names

array(['Ganesh', 'Siva', 'Murthuza', 'Anant', 'Padma'], 
      dtype='|S8')

In [96]:
copy_participant_names

array(['Ganesh', 'Siva', 'Murthuza', 'Anant', 'Padma'], 
      dtype='|S8')

In [97]:
copy_participant_names is participant_names

False

In [98]:
copy_participant_names[3]= 'Naman'

In [99]:
copy_participant_names

array(['Ganesh', 'Siva', 'Murthuza', 'Naman', 'Padma'], 
      dtype='|S8')

In [100]:
participant_names

array(['Ganesh', 'Siva', 'Murthuza', 'Anant', 'Padma'], 
      dtype='|S8')

In [101]:
participant = np.array(['Ganesh','Siva','Murthuza','Anant','Padma'])

In [102]:
view_participant = participant.view()

In [103]:
view_participant is participant

False

In [104]:
participant

array(['Ganesh', 'Siva', 'Murthuza', 'Anant', 'Padma'], 
      dtype='|S8')

In [105]:
view_participant

array(['Ganesh', 'Siva', 'Murthuza', 'Anant', 'Padma'], 
      dtype='|S8')

In [106]:
view_participant[3]='Naman'

In [107]:
view_participant

array(['Ganesh', 'Siva', 'Murthuza', 'Naman', 'Padma'], 
      dtype='|S8')

In [108]:
participant

array(['Ganesh', 'Siva', 'Murthuza', 'Naman', 'Padma'], 
      dtype='|S8')

In [109]:
assign = np.array(['Ganesh','Siva','Murthuza','Anant','Padma'])

In [110]:
assign_check = assign

In [111]:
assign_check is assign

True

In [112]:
check_sqrt = np.sqrt([1,2,3,9,16,25,36])

In [113]:
check_sqrt

array([ 1.        ,  1.41421356,  1.73205081,  3.        ,  4.        ,
        5.        ,  6.        ])

In [114]:
from numpy import pi
np.cos(0)

1.0

In [115]:
np.sin(pi/2)

1.0

In [116]:
np.cos(pi)

-1.0

In [117]:
np.floor([1,2,3,4-1273.8,182837])

array([  1.00000000e+00,   2.00000000e+00,   3.00000000e+00,
        -1.27000000e+03,   1.82837000e+05])

In [118]:
np.exp([0,1,5])

array([   1.        ,    2.71828183,  148.4131591 ])

In [119]:
aa_manipulate = np.array([[10,20,30,40],[15,25,35,45]])

In [120]:
aa_manipulate.ravel()

array([10, 20, 30, 40, 15, 25, 35, 45])

In [122]:
aa_manipulate.reshape(4,2)

array([[10, 20],
       [30, 40],
       [15, 25],
       [35, 45]])

In [130]:
np.hsplit(aa_manipulate,4)

[array([[10],
        [15]]), array([[20],
        [25]]), array([[30],
        [35]]), array([[40],
        [45]])]

In [124]:
set_1 = np.array([1,2,3,4,5])

In [125]:
set_2 = np.array([-1,-2,-3,-4,-5])

In [131]:
np.hstack((set_2,set_1,set_4))

array([-1, -2, -3, -4, -5,  1,  2,  3,  4,  5])

In [132]:
array_a = np.array([1,2,3,4])
array_b = np.array([1,1,1,1])

In [133]:
array_a * array_b

array([1, 2, 3, 4])

In [134]:
c = 0.3

In [135]:
array_a * c

array([ 0.3,  0.6,  0.9,  1.2])

In [136]:
array_d = np.array([5,6,7,8])

In [137]:
array_a * array_d

array([ 5, 12, 21, 32])

In [138]:
array_e = np.array([1,5])

In [139]:
array_a * array_e

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [140]:
aa_manipulate = np.array([[10,20,30,40],[15,25,35,45]])

In [142]:
aa_manipulate

array([[10, 20, 30, 40],
       [15, 25, 35, 45]])

In [143]:
new_array = aa_manipulate.transpose()

In [144]:
new_array

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [151]:
abc = np.array([[1,20],[22,32]])

In [152]:
abc

array([[ 1, 20],
       [22, 32]])

In [153]:
np.trace(abc)

33

In [146]:
sq_array = np.array([[1,2],[3,4]])

In [147]:
np.linalg.inv(sq_array)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])